sonar.projectKey=kinema_workbench
sonar.organization=kinema
sonar.host.url=https://sonarcloud.io

sonar.sources=crates,apps
sonar.test.inclusions=**/tests/**
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/target/**
sonar.coverage.exclusions=apps/kinema/src/main.rs

sonar.rust.lcov.reportPaths=lcov.info
